### ISSUE TITLE
Bugged with pre-patch 7/27/2018

### ISSUE THREAD

**Issue by Tanae** [Benio101/Aye#1]
Message: Interface\AddOns\Aye\Aye.lua:136: Interface\AddOns\Aye.AutoReadyCheck\utils/Buffs.lua:64: Usage: UnitBuff("unit", [index][, "filter"])
Time: Thu Jul 26 22:55:36 2018
Count: 3
Stack: Interface\AddOns\Aye\Aye.lua:136: Interface\AddOns\Aye.AutoReadyCheck\utils/Buffs.lua:64: Usage: UnitBuff("unit", [index][, "filter"])
[C]: in function `error'
Interface\AddOns\Aye\Aye.lua:136: in function <Interface\AddOns\Aye\Aye.lua:128>

Locals: (*temporary) = "Interface\AddOns\Aye.AutoReadyCheck\utils/Buffs.lua:64: Usage: UnitBuff("unit", [index][, "filter"])"

**Comment by Benio101** [comment]
Hey, this issue was actually related to [Aye.AutoReadyCheck](https://github.com/Benio101/Aye.AutoReadyCheck), indirectly. Most likely, Blizzard removed one of Buffs from game with prepatch, what caused mentioned error.

I'm sorry to say, but I left WoW and I am unable to maintain WoW addons anymore.
I suggest you installing one of alternative addons. I'm sorry for inconvenience.

Best regards.
